# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafee', '0003_auto_20171115_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='booked',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
