# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafee', '0006_auto_20171116_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='pos_X',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='pos_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
